# Site settings
title: Seminaris ISGlobal
header-img: img/1.JPG
email: joe@gmail.com
description: "Seminaris ISGlobal"
url: "http://seminaris.github.io"
# twitter_username: bcndata
# github_username:  joebrew
# facebook_username:  joebrew

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
